---
- name: Ensure IPv6 is disabled (3.3.3)
  remote_user: root
  become: yes
  hosts: linux2
  tasks:
     - name: Disabling IPv6
       lineinfile: 
         path: /etc/modprobe.d/CIS.conf
         line: 
           options ipv6 disable=1
