---
- name: Ensure telnet client is not installed (2.3.4)
  hosts: debian
  tasks:
     - name: Removing Telnet Client
       shell: 
         apt remove telnet -y
       args: 
         executable: /bin/bash

