---
- name: Ensure login and logout events are collected (4.1.7)
  hosts: debian
  tasks:
     - name: Creating Neccessary file
       file:
         path: /etc/audit/rules.d/logins.rules
         state: touch
     - name: Generating login and logout logs
       blockinfile:
         path: /etc/audit/rules.d/logins.rules
         block: |
           -w /var/log/faillog -p wa -k logins 
           -w /var/log/lastlog -p wa -k logins 
           -w /var/log/tallylog -p wa -k logins