---
- name: Ensure IP forwarding is disabled (3.1.1)
  remote_user: root
  become: yes
  hosts: linux2
  tasks:
     - name: Disabling IP Forwarding
       blockinfile:
         path: /etc/sysctl.conf
         block: |
          net.ipv4.ip_forward = 0
     - name: Executing Shell Commands
       shell: |
         sysctl -w net.ipv4.ip_forward=0
         sysctl -w net.ipv4.route.flush=1
       args:
         executable: /bin/bash
     
