---
- name: Ensure password reuse is limited (5.3.3)
  remote_user: root
  become: yes
  hosts: linux2
  tasks:
     - name: Configuring /etc/pam.d/system-auth file
       replace: 
         path: /etc/pam.d/system-auth 
         regexp: 'use_authtok$'
         replace: 'use_authtok remember=5'
     - name: Configuring /etc/pam.d/password-auth file
       replace: 
         path: /etc/pam.d/password-auth 
         regexp: 'use_authtok$'
         replace: 'use_authtok remember=5'