---
- name: Ensure sticky bit is set on all world-writable directories (1.1.21)
  hosts: debian
  tasks:
     - name: Applying Sticky Bit
       shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
       args:
         executable: /bin/bash
