---
- name: Ensure changes to system administration scope (sudoers) is collected (4.1.15)
  remote_user: root
  become: yes
  hosts: linux2
  tasks:
     - name: Setting Up Sudoers Log
       blockinfile:
         path: /etc/audit/audit.rules
         block: |
           -w /etc/sudoers -p wa -k scope 
           -w /etc/sudoers.d -p wa -k scope

