---
- name: Ensure SSH warning banner is configured (5.2.16)
  remote_user: root
  become: yes
  hosts: linux2
  tasks:
     - name: Adding Banner in /etc/issue.net file
       blockinfile: 
         path: /etc/issue.net
         block: 
           'This computer system is for authorized users only. Individuals using this
           system without authority or in excess of their authority are subject to
           having all their activities on this system monitored and recorded or
           examined by any authorized person, including law enforcement, as system
           personnel deem appropriate. In the course of monitoring individuals
           improperly using the system or in the course of system maintenance, the
           activities of authorized users may also be monitored and recorded. Any
           material so recorded may be disclosed as appropriate. Anyone using this
           system consents to these terms.'
     - name: Adding Banner Path into /etc/ssh/sshd_config file
       lineinfile:
         path: /etc/ssh/sshd_config
         line:
           'Banner /etc/issue.net'
     - name: Restarting ssh Service
       service:
         name: sshd
         state: restarted    