---
- name: Ensure iptables is installed (3.6.1)
  remote_user: root
  become: yes
  hosts: linux2
  tasks:
     - name: Installing Iptables
       yum:
         name: iptables
         state: present
