---
- name: Ensure TCP Wrappers is installed (3.4.1)
#  remote_user: root
# become: yes
  hosts: linux2
  tasks:
     - name: Installing tcp_wrappers
       yum:
         name: tcp_wrappers
         state: present
