---
- name: Ensure access to the su command is restricted (5.6)
  remote_user: root
  become: yes
  hosts: linux2
  tasks:
    - name: Restricting Users to switch to Another User
      lineinfile:
        path: /etc/pam.d/su
        line: 
          'auth required pam_wheel.so use_uid'
    - name: Configuring /etc/group file
      replace:
        path: /etc/group
        regexp:
          '^wheel:x:10:'
        replace: 
          'wheel:x:10:root,user1'