---
- name: Disable Root Login
  hosts: linux2
  tasks:
    - name: configure sshd
      replace: 
        path: /etc/ssh/sshd_config
        regexp: '#PermitRootLogin yes'
        replace: PermitRootLogin no
      notify: restart sshd
  handlers:
    - name: restart sshd
      service: 
        name: sshd
        state: restarted
